/**
 * プラン制限定義
 */
export const PLAN_LIMITS = {
  free: {
    maxProducts: 200,
    maxImages: 2000,
    maxMembers: 3,
    maxTeams: 1,
    bulkDownload: false,
    topImageDownload: false,
    uploadNotification: false,
    activityLog: false,
    memberPermissions: false,
    imageMemoTag: false,
    multipleTeams: false,
    csvApiExport: false,
  },
  lite: {
    maxProducts: 1000,
    maxImages: 10000,
    maxMembers: 5,
    maxTeams: 1,
    bulkDownload: true,
    topImageDownload: true,
    uploadNotification: true,
    activityLog: false,
    memberPermissions: false,
    imageMemoTag: false,
    multipleTeams: false,
    csvApiExport: false,
  },
  standard: {
    maxProducts: 2000,
    maxImages: 20000,
    maxMembers: 15,
    maxTeams: 1,
    bulkDownload: true,
    topImageDownload: true,
    uploadNotification: true,
    activityLog: true,
    memberPermissions: true,
    imageMemoTag: true,
    multipleTeams: false,
    csvApiExport: false,
  },
  pro: {
    maxProducts: 10000,
    maxImages: 100000,
    maxMembers: 999,
    maxTeams: 999,
    bulkDownload: true,
    topImageDownload: true,
    uploadNotification: true,
    activityLog: true,
    memberPermissions: true,
    imageMemoTag: true,
    multipleTeams: true,
    csvApiExport: true,
  },
};
