name = "detauri-ops"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
APP_NAME = "デタウリ業務"

[[d1_databases]]
binding = "DB"
database_name = "detauri-ops-db"
database_id = "87590587-b296-471c-9dcb-d5639a74ad2a"

[[kv_namespaces]]
binding = "SESSIONS"
id = "938afc39d45c4797a234108615c33afa"

[[kv_namespaces]]
binding = "CACHE"
id = "4e4da3dda9614c25bb5dc59b56815166"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "detauri-ops-images"
